### ISSUE TITLE
CB's DepLoader was unable to delete file .\mods\PotionExtension-1.7.10-1.1.0.jar

### ISSUE THREAD

**Issue by wendrom** [BreakfastCraft/BreakfastSpecial#12]
Experiencing a crash when starting up a brand new Breakfast Special 1.0.2 Server from Atlauncher.
I am running it on Windows 10 Pro 64-bit with Java 8 installed.

Crash log: [http://pastebin.com/EXFFgUyt](http://pastebin.com/EXFFgUyt)

Along with the log was a dialog box instructing I delete the PotionExtension jar file.
This error is preventing me from running the server, and I would like to keep PotionExtension if I can.

**Comment by topher2010** [comment]
I find this wierd because the PotionExtension mod isn't in the main mods folder, it's in the 1.7.10 folder inside the mods folder.  I'll look into possible solutions and get back to you.

**Comment by wendrom** [comment]
That's the case with 1.0.1, but not with 1.0.2 of the Breakfast Special version.

**Comment by topher2010** [comment]
Can you try redownloading the server from the launcher?  PotionExtension should now only appear in the 1.7.10 folder.

**Comment by wendrom** [comment]
It works for me now, thanks.

**Comment by topher2010** [comment]
Perfect.  Thanks for the reply.
