### ISSUE TITLE
No class definition found error: EntityClientPlayerMP

### ISSUE THREAD

**Issue by wendrom** [BreakfastCraft/BreakfastSpecial#13]
I think there might be some client mods included in the server version when downloaded through Atlauncher and it's causing this error:

[http://pastebin.com/zurVs4RF](http://pastebin.com/zurVs4RF)

**Comment by wendrom** [comment]
It seems to be an issue with the mod Chance Cubes which they noted to have fixed with their newest version (1.3.6.29).

[http://minecraft.curseforge.com/mc-mods/233113-chance-cubes/files/2259998](http://minecraft.curseforge.com/mc-mods/233113-chance-cubes/files/2259998)

**Comment by topher2010** [comment]
I'll work on a new version very soon to resolve this issue.  I'll update this issue once I do.

**Comment by topher2010** [comment]
Just letting you know I will be working on this issue tonight when I get home from work.  I will let you know once I have this build together and have tested it working.

**Comment by wendrom** [comment]
Updating the mod on both the client and server fixed the issue for me at least. I'm looking forward to trying out this pack with my friends now. Huzzah!

**Comment by demethan** [comment]
we are testing dev.1.0.3 tonight with your fix. thx

**Comment by topher2010** [comment]
This fix has been pushed live to version 1.0.3
