### ISSUE TITLE
Mark of the Falling Tower doesn't seem to work.

### ISSUE THREAD

**Issue by stephanstross** [BreakfastCraft/BreakfastSpecial#17]
In the Blood Magic Guide-API book, it states that the "Mark of the Falling Tower" ritual costs 1M LP to activate, yet when attempting to activate the ritual, with an awakened activation crystal, and over 3M LP in my soul network, it gives the "You feel a pull..." message. It seems to think that I don't have enough LP to activate the ritual, though the book says I does. I was unable to find any blood magic config options explicitly banning or increasing the cost of the ritual. Do you have any insights on the problem, or any reason why this might be occurring? This may soon become problematic on the server I administrate.

**Comment by F4ndroid** [comment]
That message usually indicates that the activation crystal has not been bound to a player. Right-click with it in the air before you right-click on the master ritual stone. Also, try activating it with a creative crystal.

**Comment by knife-wizard** [comment]
You cannot comprehend the true form of my derp. Can't believe I forgot the most basic of sanity checks. It really SHOULD give a different message for unbound items, but thanks for reminding me to do that. It works fine now.
