### ISSUE TITLE
Misaligned text in the Sanguine Scientiem

### ISSUE THREAD

**Issue by stephanstross** [BreakfastCraft/BreakfastSpecial#18]
This error occurs in the version of Blood Magic in the latest version of The Breakfast Special modpack, on the ATLauncher. The text of the sanguine scientiem is not correctly aligned on the page, and the bottom half of most pages of text comes off the page, making the book pretty much unreadable. I've attached a screenshot of the issue.
![image](https://cloud.githubusercontent.com/assets/1668360/12155944/1a866982-b496-11e5-9316-385acef0dec6.png)

EDIT: cross-posted to the Blood Magic github:
https://github.com/WayofTime/BloodMagic/issues/549

**Comment by topher2010** [comment]
Closing this issue as the rework of the modpack is going to 1.10.2
