### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by tw34ksource** [BreakfastCraft/BreakfastSpecial#20]
Breakfast Special 10.5

Fresh download on 3/12. Java heap errors. Server will not run.

[crash-2016-03-12_23.13.15-server.txt](https://github.com/BreakfastCraft/BreakfastSpecial/files/170790/crash-2016-03-12_23.13.15-server.txt)

**Comment by demethan** [comment]
From the report I think you are still on java 7 update 80.. I think you need java 8

Make sure you don't have any client side mods on the server. Like better title screen or armor status..

Hope this helps.

**Comment by topher2010** [comment]
I am closing this ticket as the new version of Breakfast Special will be a rework for 1.10.2
