### ISSUE TITLE
Iguana Tweaks client/server config mismatch

### ISSUE THREAD

**Issue by F4ndroid** [BreakfastCraft/BreakfastSpecial#9]
Server config (IguanaTinkerTweaks/main.cfg):
B:pickaxeBoostRequired=false

Client config:
B:pickaxeBoostRequired=true

Causes tools to display "this tool has incorrect data..." on the client.

Server config (IguanaTinkerTweaks/modules.cfg):
B:MobHeads=false

B:Restrictions=false

B:HarvestLevelTweaks=false

Client config:
B:MobHeads=true

B:Restrictions=true

B:HarvestLevelTweaks=true

Change the client configs to match the server configs as explained here to solve. As it stands I can't mine obsidian with an alumite pick and applying a diamond does nothing to fix that. This happened after I updated to 1.0.

**Comment by topher2010** [comment]
Try redownloading the pack.  My client side configs match the server side configs.  Also, the server download and the client download use the same configs.

**Comment by F4ndroid** [comment]
Creating a new instance fixed this issue.
